### ISSUE TITLE
how use?

### ISSUE THREAD

**Issue by SiSiska** [ZengSiwei/ArchiSteamFarm-IPC-SteamGrandPrix#1]
I need instructions for the kettle. plz

**Comment by ZengSiwei** [comment]
I wrote something related at the steamCN forum. [LINK](https://steamcn.com/t501091-1-1)
Maybe you can read the content with Google Translate and use it.

**Comment by SiSiska** [comment]
it was not as difficult as it seemed. Of course, I still have questions, but the language barrier does not allow to get a full answer to them. thank

**Comment by ZengSiwei** [comment]
(●'◡'●)
